name: oauth_webauth
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/luis901101/oauth_webauth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  webview_flutter: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: